# Generated by Django 3.2.3 on 2021-05-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='welcome', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='take', max_length=255),
            preserve_default=False,
        ),
    ]
