# Generated by Django 3.2.3 on 2021-05-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default='hello', max_length=255, unique=True),
        ),
    ]
